language: r
r:
  - oldrel
  - release
  - devel
repos:
    CRAN: https://cloud.r-project.org
    ropensci: http://packages.ropensci.org
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - LINTR_COMMENT_BOT=false
    - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
install:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (!require("git2r")) install.packages("git2r")'
  - Rscript -e 'if (!require("devtools")) install.packages("devtools")'
  - Rscript -e 'if (!require("roxygen2")) devtools::install_github("klutometis/roxygen@v5.0.1")'
  - Rscript -e 'if (!require("lintr")) devtools::install_github("jimhester/lintr")'
  - Rscript -e 'if (!require("covr")) devtools::install_github("jimhester/covr")'
  - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
script:
  - Rscript -e 'try(devtools::install(".")); r <- rcmdcheck::rcmdcheck(".", args = c("--no-manual")); l <- lintr::lint_package("."); print(l); quit(save = "no", status = if (length(c(r$errors, r$warnings, l)) > 1 || grepl("FAILED", r$output$stdout)) { 1 } else { 0 }, runLast = FALSE)'
after_success:
  - Rscript -e 'library(covr);codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
