sudo: required
language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r testthat crayon"
- "./travis-tool.sh install_github jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: fEz6PnKZw03WaGCo9Ivqx743IaZWHARKrb6jbi1Q68oh/KY8xSLsgZpO7ooj3bRK0C+GIWZtAWBJ1BDjx0UKARRaWNkTDP5kLXrsOaGyiZPvtb2nQR5yqk/vy1c0wuA49O0qMGw9q6kEG7/jC5Hi+27oN1fDKPZyqhgnEh8WoHA=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"

env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
